const ALLOWED=["nike.com","www.nike.com","nike.sng.link","zalando.de","www.zalando.de","amazon.de","www.amazon.de","saturn.de","www.saturn.de","peek-cloppenburg.de","www.peek-cloppenburg.de","aboutyou.de","www.aboutyou.de","adidas.de","www.adidas.de","cyberport.de","www.cyberport.de"];
function allowed(h){h=String(h||"").toLowerCase();return ALLOWED.some(d=>h===d||h.endsWith("."+d))}
function num(v){if(v==null)return null;let s=String(v).replace(/\u00a0/g," ").replace(/[€$£]/g,"").trim().replace(/[^\d.,]/g,"");if(!s)return null;if(s.includes(".")&&s.includes(",")){s=s.lastIndexOf(",")>s.lastIndexOf(".")?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"")}else if(s.includes(","))s=s.replace(",",".");const n=Number(s);return Number.isFinite(n)&&n>0&&n<100000?Math.round(n*100)/100:null}
function add(a,v,s,p){const price=num(v);if(price!=null)a.push({price,source:s,priority:p})}
function parsePrice(html){const a=[];const ld=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;
while((m=ld.exec(html))){try{const visit=o=>{if(!o||typeof o!=="object")return;if(Array.isArray(o))return o.forEach(visit);if(String(o["@type"]||"").toLowerCase()==="product"){const x=o.offers;(Array.isArray(x)?x:[x]).filter(Boolean).forEach(z=>{add(a,z.price,"JSON-LD Product Offer",100);add(a,z.lowPrice,"JSON-LD Product Offer",95)})}Object.values(o).forEach(visit)};visit(JSON.parse(m[1]))}catch{}}
for(const [r,s,p] of [[/<meta[^>]+property=["']product:price:amount["'][^>]+content=["']([^"']+)/i,"Meta product:price",90],[/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']product:price:amount["']/i,"Meta product:price",90],[/<meta[^>]+itemprop=["']price["'][^>]+content=["']([^"']+)/i,"Meta itemprop price",85],[/<meta[^>]+content=["']([^"']+)["'][^>]+itemprop=["']price["']/i,"Meta itemprop price",85]]){const x=html.match(r);if(x)add(a,x[1],s,p)}
for(const [r,s,p] of [[/"currentPrice"\s*:\s*"?([0-9]+(?:[.,][0-9]{1,2})?)"?/gi,"currentPrice",75],[/"salePrice"\s*:\s*"?([0-9]+(?:[.,][0-9]{1,2})?)"?/gi,"salePrice",70],[/"price"\s*:\s*"?([0-9]+(?:[.,][0-9]{1,2})?)"?/gi,"price",40]]){let x,c=0;while((x=r.exec(html))&&c++<30)add(a,x[1],s,p)}
if(!a.length)return{price:null,source:"Kein Preis erkannt"};a.sort((x,y)=>y.priority-x.priority);return a[0]}
function out(statusCode,data){return new Response(JSON.stringify(data),{status:statusCode,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"POST, OPTIONS","access-control-allow-headers":"Content-Type"}})}
export async function onRequest(context){const event={httpMethod:context.request.method,body:await context.request.text()};if(event.httpMethod==="OPTIONS")return out(200,{ok:true});if(event.httpMethod!=="POST")return out(405,{error:"Nur POST erlaubt"});
try{let body;try{body=JSON.parse(event.body||"{}")}catch{return out(400,{error:"Ungültige Anfrage."})}if(!body.url||typeof body.url!=="string")return out(400,{error:"Bitte eine Produkt-URL angeben."});
let u;try{u=new URL(body.url)}catch{return out(400,{error:"Ungültiger Produktlink."})}if(u.protocol!=="https:"||!allowed(u.hostname))return out(400,{error:"Dieser Shop wird noch nicht unterstützt."});
const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);let r;try{r=await fetch(u.toString(),{redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"de-DE,de;q=0.9,en;q=0.8"}})}finally{clearTimeout(t)}
const f=new URL(r.url);if(!allowed(f.hostname))return out(400,{error:"Weiterleitung zu einer nicht unterstützten Domain."});if(!r.ok)return out(502,{error:"Shop antwortete mit HTTP "+r.status});if(!(r.headers.get("content-type")||"").toLowerCase().includes("text/html"))return out(502,{error:"Keine Produktseite erhalten."});
const q=parsePrice((await r.text()).slice(0,3000000));return out(200,{price:q.price,currency:"EUR",url:f.toString(),source:q.source,checkedAt:new Date().toISOString()})
}catch(e){if(e&&e.name==="AbortError")return out(504,{error:"Die Produktseite hat zu lange für eine Antwort gebraucht."});console.error("check-price error:",e);return out(400,{error:"Produktlink konnte nicht geprüft werden."})}};
